<?php

/** @var Dashboard $block */

use ChannelEngine\ChannelEngineIntegration\Block\Adminhtml\Content\Dashboard;

?>
<script src="<?= $block->escapeHtml($block->getViewFileUrl('ChannelEngine_ChannelEngineIntegration::js/TriggerSyncService.js')) ?>"></script>
<script src="<?= $block->escapeHtml($block->getViewFileUrl('ChannelEngine_ChannelEngineIntegration::js/Enable.js'))?>"></script>
<div class="ce-page ce-disabled-page">
    <p>
        <?= $block->escapeHtml('Integration between Magento 2 and ChannelEngine is disabled. Synchronization is not performed in the background.') ?>
    </p>
    <p style="display: <?= $block->shouldRenderIntegrationDisabledThreeLevelSyncMessage() ? '' : 'none'; ?>">
        <?= $block->escapeHtml('The integration is disabled because the product attribute which corresponds with the chosen  three level sync attribute was deleted in the shop.') ?>
    </p>
    <div class="ce-disable-page-content">
        <div class="ce-input-group">
            <label>
                <span class="label"><?= $block->escapeHtml('Enable the integration') ?></span>
                <span class="ce-help">
                    <span class="ce-help-tooltip">
                        <?= $block->escapeHtml('By enabling integration, you will be asked whether you want to perform full synchronization (products and orders) again since synchronization was disabled for some time.') ?>
                    </span>
                </span>
                <label class="ce-switch">
                    <input id="ce-enable-switch" type="checkbox">
                    <span class="ce-switch__slider"></span>
                </label>
            </label>
        </div>
    </div>
    <input id="ce-trigger-sync-url" type="hidden"
           value="<?= $block->escapeHtml($block->getTriggerSyncUrl()) ?>">
    <input id="ce-check-status-url" type="hidden"
           value="<?= $block->escapeHtml($block->getCheckStatusUrl()) ?>">
    <div id="ce-trigger-modal" class="ce-hidden">
        <?=  $block->getLayout()->createBlock(Dashboard::class)
            ->setTemplate("ChannelEngine_ChannelEngineIntegration::partials/triggerSync.phtml")->toHtml();
        ?>
    </div>
</div>