<?php

/** @var Notifications $block */

use ChannelEngine\ChannelEngineIntegration\Block\Adminhtml\Dashboard\Notifications;

?>
<div class="ce-page ce-horizontal ce-notifications-page">
    <script src="<?= $block->escapeHtml($block->getViewFileUrl('ChannelEngine_ChannelEngineIntegration::js/DashboardNotifications.js')) ?>">
    </script>
    <script src="<?= $block->escapeHtml($block->getViewFileUrl('ChannelEngine_ChannelEngineIntegration::js/ModalService.js')) ?>">
    </script>
    <script src="<?= $block->escapeHtml($block->getViewFileUrl('ChannelEngine_ChannelEngineIntegration::js/Details.js')) ?>">
    </script>
    <img src="<?= $block->escapeHtml($block->getViewFileUrl('ChannelEngine_ChannelEngineIntegration::images/warning.png')) ?>"
         alt="" class="ce-icon__big">
    <div class="ce-notifications">
        <h2><?= $block->escapeHtml('Notifications'); ?></h2>
        <div class="ce-notifications__items">
            <div class="ce-notifications__load-more">
                <button id="ce-load-more-btn" class="ce-button ce-button__primary"><?= $block->escapeHtml('Load more'); ?></button>
            </div>
        </div>
    </div>
    <input id="ce-notifications-url" type="hidden"
           value="<?= $block->escapeHtml($block->getNotificationUrl()) ?>">
    <input id="ce-details-url" type="hidden"
           value="<?= $block->escapeHtml($block->getNotificationDetailsUrl()) ?>">
    <input id="ce-details-get" type="hidden"
           value="<?= $block->escapeHtml($block->getDetailsUrl()) ?>">
    <input id="ce-show-details-text" type="hidden" value="<?= $block->escapeHtml('Show details') ?>">
    <input id="ce-details-header" type="hidden" value="<?= $block->escapeHtml('Transaction log details') ?>">
    <input id="ce-modal-button-text" type="hidden" value="<?= $block->escapeHtml('Close') ?>">
    <input id="ce-details-identifier" type="hidden" value="<?= $block->escapeHtml('Identifier') ?>">
    <input id="ce-details-message" type="hidden" value="<?= $block->escapeHtml('Message') ?>">
    <input id="ce-details-display" type="hidden" value="<?= $block->escapeHtml('Displayed') ?>">
    <input id="ce-details-to" type="hidden" value="<?= $block->escapeHtml('to') ?>">
    <input id="ce-details-from" type="hidden" value="<?= $block->escapeHtml('of') ?>">
    <input id="ce-details-page-size" type="hidden" value="<?= $block->escapeHtml('Page size:') ?>">
    <input id="ce-details-go-to-previous" type="hidden"
           value="<?= $block->escapeHtml('Go to previous page') ?>">
    <input id="ce-details-previous" type="hidden" value="<?= $block->escapeHtml('Previous') ?>">
    <input id="ce-details-go-to-next" type="hidden" value="<?= $block->escapeHtml('Go to next page') ?>">
    <input id="ce-details-next" type="hidden" value="<?= $block->escapeHtml('Next') ?>">
    <input id="ce-notifications-offset" type="hidden" value="0">
</div>
<div id="ce-modal" class="ce-hidden">
    <?=  $block->getLayout()->createBlock(Notifications::class)
        ->setTemplate("ChannelEngine_ChannelEngineIntegration::partials/modal.phtml")->toHtml();
    ?>
</div>