<?php

/** @var ReturnsSettings $block */

use ChannelEngine\ChannelEngineIntegration\Block\Adminhtml\Content\ReturnsSettings;

$itemConditions = $block->getItemConditions();
$itemResolutions = $block->getItemResolution();
$returnsSettings = $block->getReturnsSettings();

$defaultCondition = '';
$defaultReason = '';

if ($returnsSettings) {
    foreach ($itemConditions as $condition) {
        if ($condition['value'] === $returnsSettings->getDefaultCondition()) {
            $defaultCondition = $condition['label'];
        }
    }

    foreach ($itemResolutions as $resolution) {
        if ($resolution['value'] === $returnsSettings->getDefaultResolution()) {
            $defaultReason = $resolution['label'];
        }
    }
}

?>
<form class="ce-form" onsubmit="return false">
    <h3><?= __("Marketplace returns") ?></h3>
    <div class="ce-input-group ce-flex">
        <label>
            <span class="label"><?= __('Import marketplace returns'); ?></span>
            <span class="ce-help">
                <span class="ce-help-tooltip">
                    <?= __('If this field is checked, marketplace returns will be downloaded from ChannelEngine.'); ?>
                </span>
            </span>
        </label>
        <div class="ce-dropdown-wrapper">
            <button id="ce-returns" class="ce-dropdown" returns-enabled="<?= !$returnsSettings || $returnsSettings->isReturnsEnabled() ? '1' : '0'?>">
                <span id="ce-returns-text" class="ce-dropdown-text">
                    <?= !$returnsSettings || $returnsSettings->isReturnsEnabled() ? __('Yes') : __('No');?>
                </span>
            </button>
            <div class="ce-dropdown-menu">
                <ul id="ce-returns-list" class="ce-dropdown-list">
                    <li id="ce-returns-item-yes" class="ce-dropdown-list-item" value="1">
                        <span class="ce-dropdown-list-item-text"><?= __('Yes');?></span>
                    </li>
                    <li id="ce-returns-item-no" class="ce-dropdown-list-item" value="0">
                        <span class="ce-dropdown-list-item-text"><?= __('No');?></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="ce-input-group ce-flex">
        <label>
            <span class="label"><?= __('Default item condition'); ?></span>
            <span class="ce-help">
                <span class="ce-help-tooltip">
                    <?= __('Please select the default item condition that will be used when importing a return request from ChannelEngine.'); ?>
                </span>
            </span>
        </label>
        <div class="ce-dropdown-wrapper">
            <button id="ce-default-condition" class="ce-dropdown" data-default-condition="
            <?= $returnsSettings ? $returnsSettings->getDefaultCondition() : ''; ?>"
            <?= !$returnsSettings || $returnsSettings->isReturnsEnabled() ? '' : 'disabled=true'?>
            >
                <span id="ce-default-condition-text" class="ce-dropdown-text">
                    <?= $defaultCondition; ?>
                </span>
            </button>
            <div class="ce-dropdown-menu">
                <ul id="ce-default-condition-list" class="ce-dropdown-list">
                    <?php
                    foreach ($itemConditions as $itemCondition) {
                        echo '<li class="ce-dropdown-list-item ce-condition-item" value="' . $itemCondition['value'] . '">
                              <span class="ce-dropdown-list-item-text">'
                            . $itemCondition['label'] . '</span></option>';
                    }
                    ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="ce-input-group ce-flex">
        <label>
            <span class="label"><?= __('Default item resolution'); ?></span>
            <span class="ce-help">
                <span class="ce-help-tooltip">
                    <?= __('Please select the default item resolution that will be used when importing a return request from ChannelEngine.'); ?>
                </span>
            </span>
        </label>
        <div class="ce-dropdown-wrapper">
            <button id="ce-default-resolution" class="ce-dropdown" data-default-resolution="
            <?= $returnsSettings ? $returnsSettings->getDefaultResolution() : ''; ?>"
            <?= !$returnsSettings || $returnsSettings->isReturnsEnabled() ? '' : 'disabled=true'?>
            >
                <span id="ce-default-resolution-text" class="ce-dropdown-text">
                    <?= $defaultReason; ?>
                </span>
            </button>
            <div class="ce-dropdown-menu">
                <ul id="ce-default-resolution-list" class="ce-dropdown-list">
                    <?php
                    foreach ($itemResolutions as $itemResolution) {
                        echo '<li class="ce-dropdown-list-item ce-resolution-item" value="' . $itemResolution['value'] . '">
                              <span class="ce-dropdown-list-item-text">'
                            . $itemResolution['label'] . '</span></option>';
                    }
                    ?>
                </ul>
            </div>
        </div>
    </div>
</form>
