<?php

/**  @var ProductSync $block */

use ChannelEngine\ChannelEngineIntegration\Block\Adminhtml\Content\ProductSync;

$sources = $block->getInventorySources();
$selectedSourceId = '';

if (!empty($sources[0])) {
    $selectedSourceId = $sources[0]['value'];
}

$stockSettings = $block->getStockSettings();

?>
<form class="ce-form" onsubmit="return false">
    <h3><?= $block->escapeHtml("Stock synchronization") ?></h3>
    <div id="ce-enable-msi-warning" class="ce-sku-warning" style="width: fit-content; display: <?= $block->isMSIEnabledInShop() ? 'none' : ''; ?>">
        <?= $block->escapeHtml('Please enable the Magento Multi-Source Inventory module in order to enable it in the ChannelEngine configuration.') ?>
    </div>
    <div class="ce-input-group ce-flex">
        <label>
            <span class="label"><?= $block->escapeHtml('Enable stock synchronization') ?></span>
            <span class="ce-help">
                <span class="ce-help-tooltip">
                    <?= $block->escapeHtml('If this field is checked, stock product information will be synced to the ChannelEngine.') ?>
                </span>
            </span>
        </label>
        <div class="ce-dropdown-wrapper">
            <button id="ce-stock" class="ce-dropdown" stock-enabled="<?= !$stockSettings || $stockSettings->isEnableStockSync() ? 1 : 0?>">
                <span id="ce-stock-text" class="ce-dropdown-text">
                    <?= !$stockSettings || $stockSettings->isEnableStockSync() ? $block->escapeHtml('Yes') : $block->escapeHtml('No');?>
                </span>
            </button>
            <div class="ce-dropdown-menu">
                <ul id="ce-stock-list" class="ce-dropdown-list">
                    <li id="ce-stock-item-yes" class="ce-dropdown-list-item" value="1">
                        <span class="ce-dropdown-list-item-text"><?= $block->escapeHtml('Yes')?></span>
                    </li>
                    <li id="ce-stock-item-no" class="ce-dropdown-list-item" value="0">
                        <span class="ce-dropdown-list-item-text"><?= $block->escapeHtml('No')?></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="ce-input-group ce-flex">
        <label>
            <span class="label"><?= $block->escapeHtml('Enable MSI') ?></span>
            <span class="ce-help">
                <span class="ce-help-tooltip"><?= $block->escapeHtml('Enable using Multi-Source Inventory.') ?></span>
            </span>
        </label>
        <div class="ce-dropdown-wrapper">
            <button id="ce-enable-msi" class="ce-dropdown"
                    msi-enabled="<?= (!$stockSettings || $stockSettings->isEnableMSI()) && $block->isMSIEnabledInShop() ? 1 : 0?>"
                    msi-enabled-in-shop="<?= $block->isMSIEnabledInShop() ? 1 : 0 ?>">
                <span id="ce-msi-text" class="ce-dropdown-text">
                    <?= !$stockSettings || $stockSettings->isEnableMSI() ? $block->escapeHtml('Yes') : $block->escapeHtml('No')?>
                </span>
            </button>
            <div class="ce-dropdown-menu">
                <ul id="ce-msi-list" class="ce-dropdown-list">
                    <li id="ce-msi-item-yes" class="ce-dropdown-list-item" value="1">
                        <span class="ce-dropdown-list-item-text"><?= $block->escapeHtml('Yes')?></span>
                    </li>
                    <li id="ce-msi-item-no" class="ce-dropdown-list-item" value="0">
                        <span class="ce-dropdown-list-item-text"><?= $block->escapeHtml('No')?></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="ce-input-group ce-flex" id="ce-select-inventories-section">
        <label>
            <span class="label"><?= $block->escapeHtml('Select inventories') ?></span>
            <span class="ce-help">
                <span class="ce-help-tooltip">
                    <?= $block->escapeHtml('Please select which inventories should be used during the product synchronization. The extension will use the sum of the available items in selected sources as the amount for sync.') ?>
                </span>
            </span>
            <select id="ce-inventory-select" class="ce-stock-select" multiple <?= $stockSettings && !$stockSettings->isEnableStockSync() ? "disabled" : "";?>>
                <?php
                foreach ($sources as $source) {
                    echo '<option class="ce-stock-option" value="' . $block->escapeHtml($source['value']) . '" ' .
                        ($stockSettings && in_array($source['value'], $stockSettings->getInventories(), true) ? 'selected' : '') .
                        '>' . $block->escapeHtml($source['label']) . '</option>';
                }
                ?>
            </select>
        </label>
    </div>
    <div class="ce-input-group ce-flex">
        <label>
            <span class="label"><?= $block->escapeHtml('Set default stock quantity') ?></span>
            <span class="ce-help">
                <span class="ce-help-tooltip">
                    <?= $block->escapeHtml('Please select the default stock associated with the selected inventories.') ?>
                </span>
            </span>
            <input id="ceStockQuantity" type="text" class="ce-stock-input" value="<?= $stockSettings ? $block->escapeHtml($stockSettings->getQuantity()) : 0?>"
                <?= $stockSettings && !$stockSettings->isEnableStockSync() ? "disabled" : ""?>>&nbsp;<?= $block->escapeHtml('psc') ?>
        </label>
    </div>
</form>
